version: '3.4'

services:
  beanbotsharp.bot:
    container_name: bot
    image: ${DOCKER_REGISTRY-}beanbotsharpbot
    build:
      context: .
      dockerfile: BeanbotSharp.Bot/Dockerfile
    environment:
      DISCORD_TOKEN: ODYxMzY0Nzg1NzgxMDE0NTI4.YOIueA.2eIyaRebzDmoHH4gR1LuHYwCbLA
      GIPHY_KEY: YFzS5e8x1AnNVC2HqAgfn4AiQDLIUNvp
    depends_on:
      - beanbotsharp.api
  beanbotsharp.api:
    container_name: api
    image: ${DOCKER_REGISTRY-}beanbotsharpapi
    build:
      context: .
      dockerfile: BeanbotSharp.API/Dockerfile
    environment:
      DB_CONNECTION_STRING_RR: User ID=postgres;Password=password;Host=db;Port=5432;Database=rr
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./data/:/var/lib/postgresql/data/:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      start_period: 5s
      retries: 3