version: '3.4'
services:
  beanbotsharp.bot:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  beanbotsharp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

