version: '3.4'

services:
  beanbotsharp:
    image: ${DOCKER_REGISTRY-}beanbotsharp
    build:
      context: .
      dockerfile: BeanbotSharp/Dockerfile
    environment:
      DISCORD_TOKEN: your discord token here
      GIPHY_KEY: your giphy api key here